site_name: backend
site_description: Boilerplate django + nuxt 
repo_url: https://github.com/jasperscheper/django-nuxt-boilerplate
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/jasperscheper">jasperscheper</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
